name: Build and push documentation

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string

jobs:
  docs_build_and_push:
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image_name }}
      options: --user root
      credentials:
        username: _json_key
        password: ${{ secrets.GAR_JSON_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
          persist-credentials: false
      # lfs=true is not enough, see https://stackoverflow.com/questions/61463578/github-actions-actions-checkoutv2-lfs-true-flag-not-converting-pointers-to-act
      # config tweak is needed b/c of annoying bugs in actions/checkout, see https://github.com/actions/checkout/issues/766
      - name: Pull LFS Objects
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git lfs pull
      - name: Cache Jupyter Cache Directory
        uses: actions/cache@v4
        with:
          key: jupyter-cache-${{ runner.os }}-${{ github.ref }}-${{ inputs.python_version }}
          path: _build/.jupyter_cache
      - name: Build docs
        run: bash build_scripts/build_docs.sh
      - name: Prepare Pages
        if: github.ref_name == github.event.repository.default_branch
        run: mv _build/html/* public/
      - name: Deploy Pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: github.ref_name == github.event.repository.default_branch
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: public
          TARGET_FOLDER: .
          CLEAN: true
          SINGLE_COMMIT: true
